#pragma once

#include <linux/types.h>

#define GPIO_BASE_ADDRESS (0x7E200000)
#define GPIO_FSEL_0_OFFSET (0x00)
#define GPIO_FSEL_1_OFFSET (0x04)
#define GPIO_FSEL_2_OFFSET (0x08)
#define GPIO_SET_OFFSET (0x1C)
#define GPIO_CLR_OFFSET (0x28)
#define GPIO_FSEL_0_ADDR (GPIO_BASE_ADDRESS + GPIO_FSEL_0_OFFSET)
#define GPIO_FSEL_1_ADDR (GPIO_BASE_ADDRESS + GPIO_FSEL_1_OFFSET)
#define GPIO_FSEL_2_ADDR (GPIO_BASE_ADDRESS + GPIO_FSEL_2_OFFSET)
#define GPIO_SET_ADDR (GPIO_BASE_ADDRESS + GPIO_SET_OFFSET)
#define GPIO_CLR_ADDR (GPIO_BASE_ADDRESS + GPIO_CLR_OFFSET)
#define GPIO_FSEL_0 (*(volatile uint32_t*)GPIO_FSEL_0_ADDR)
#define GPIO_FSEL_1 (*(volatile uint32_t*)GPIO_FSEL_1_ADDR)
#define GPIO_FSEL_2 (*(volatile uint32_t*)GPIO_FSEL_2_ADDR)
#define GPIO_SET (*(volatile uint32_t*)GPIO_SET_ADDR)
#define GPIO_CLR (*(volatile uint32_t*)GPIO_CLR_ADDR)

